server:
  port: 8083

spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lza/myconfig.git
  rabbitmq:
    host: 192.168.14.128
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
